name: Deploy to EC2 on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy React and Spring Boot apps to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build React app
      run: |
        cd reactapp
        npm install
        npm run build
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
          java-version: 11.0.4

    - name: Build Spring Boot app
      run: |
        cd springapp
        ./mvnw package

