name: Deploy to EC2 on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy React and Spring Boot apps to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        echo "$EC2_SSH_PRIVATE_KEY" > paymint-server-key.pem
        chmod 600 paymint-server-key.pem

        # Stop the existing server
        ssh -i paymint-server-key.pem "$EC2_USER"@"$EC2_HOST" 'pkill -f "java -jar springapp-0.0.1-SNAPSHOT.jar"'


